use_frameworks!

target 'SwiftLayoutConstraints_Example' do
  pod 'SwiftLayoutConstraints', :path => '../'

  target 'SwiftLayoutConstraints_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
